# Generated by Django 6.1.1 on 2026-09-21 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserDefinedSSOConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="A unique name for this SSO configuration. You will need to make sure your SSO provider sends callbacks to '/complete/<name>/' where <name> is the name you provide here.",
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AzureADSSOConfig",
            fields=[
                (
                    "userdefinedssoconfig_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="social_django_user_config_sso.userdefinedssoconfig",
                    ),
                ),
                (
                    "client_id",
                    models.CharField(
                        help_text="Azure AD Application (Client) ID.", max_length=255
                    ),
                ),
                ("secret", models.CharField(max_length=255)),
                (
                    "tenant_id",
                    models.CharField(
                        blank=True,
                        help_text="Azure AD Directory (Tenant) ID.",
                        max_length=255,
                    ),
                ),
            ],
            bases=("social_django_user_config_sso.userdefinedssoconfig",),
        ),
        migrations.CreateModel(
            name="GitHubSSOConfig",
            fields=[
                (
                    "userdefinedssoconfig_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="social_django_user_config_sso.userdefinedssoconfig",
                    ),
                ),
                ("key", models.CharField(max_length=255)),
                ("secret", models.CharField(max_length=255)),
            ],
            bases=("social_django_user_config_sso.userdefinedssoconfig",),
        ),
    ]
