# Generated by Django 5.2.17 on 2026-09-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_django_user_config_sso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdefinedssoconfig',
            name='button_name',
            field=models.CharField(blank=True, help_text='A button label for the login page.', max_length=100),
        ),
        migrations.AlterField(
            model_name='azureadssoconfig',
            name='tenant_id',
            field=models.CharField(blank=True, help_text='Azure AD Directory (Tenant) ID, leave blank for a multi-tenant app.', max_length=255),
        ),
        migrations.AlterField(
            model_name='userdefinedssoconfig',
            name='name',
            field=models.CharField(help_text="A unique name for this SSO configuration. Your SSO provider must send callbacks to /complete/'name'/ where 'name' is the name you enter here.", max_length=100, unique=True),
        ),
    ]
