# Generated by Django 5.2.17 on 2026-10-01 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_django_user_config_sso', '0002_userdefinedssoconfig_button_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azureadssoconfig',
            name='client_id',
            field=models.CharField(help_text='Azure AD Application (Client) ID.', max_length=255, verbose_name='Client ID'),
        ),
        migrations.AlterField(
            model_name='azureadssoconfig',
            name='tenant_id',
            field=models.CharField(blank=True, help_text='Azure AD Directory (Tenant) ID.', max_length=255, verbose_name='Tenant ID'),
        ),
        migrations.AlterField(
            model_name='githubssoconfig',
            name='key',
            field=models.CharField(help_text='Github Application (Client) ID.', max_length=255, verbose_name='Client ID'),
        ),
        migrations.AlterField(
            model_name='userdefinedssoconfig',
            name='name',
            field=models.CharField(help_text="A unique name for this SSO configuration. Your SSO provider must send callbacks to /complete/'name'/ where 'name' is the text you enter here.", max_length=100, unique=True),
        ),
    ]
